{{- if .Values.exporter.hygon.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hami-vgpu.exporter" . }}-dcu
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hami-vgpu.exporter" . }}-dcu
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "hami-vgpu.exporter" . }}-dcu
  apiGroup: rbac.authorization.k8s.io
{{- end }}