{{- if .Values.exporter.hygon.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: {{ include "hami-vgpu.exporter" . }}-dcu
    {{- if .Values.global.prometheus.serviceMonitorSelector }}
    {{- toYaml .Values.global.prometheus.serviceMonitorSelector | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "hami-vgpu.exporter" . }}-dcu
spec:
  endpoints:
    - port: metrics
      path: /metrics
      relabelings:
        - action: replace
          sourceLabels: [ __meta_kubernetes_endpoint_node_name ]
          targetLabel: node
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hami-vgpu.exporter" . }}-dcu
{{- end }}