apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: {{ include "kubeedge.namespace" . }}
  labels:
    {{- include "kubeedge.cloudcore.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.cloudhub }}
    targetPort: {{ .Values.cloudHub.websocket.port }}
    name: cloudhub
  - port: {{ .Values.service.ports.cloudhubQuic }}
    targetPort: {{ .Values.cloudHub.quic.port }}
    protocol: UDP
    name: cloudhub-quic
  - port: {{ .Values.service.ports.cloudhubHttps }}
    targetPort: {{ .Values.cloudHub.https.port }}
    name: cloudhub-https
  - port: {{ .Values.service.ports.cloudstream }}
    targetPort: {{ .Values.cloudStream.streamPort }}
    name: cloudstream
  - port: {{ .Values.service.ports.tunnelport }}
    targetPort: {{ .Values.cloudStream.tunnelPort }}
    name: tunnelport
  selector:
    {{- include "kubeedge.cloudcore.labels" . | nindent 4 }}
