apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-duty-web.fullname" . }}
  labels:
    {{- include "simple-duty-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-duty-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-duty-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "simple-duty-web.fullname" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          capabilities:
            {{- toYaml .Values.securityContext.capabilities | nindent 12 }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
