{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-duty-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-duty-web.labels" . | nindent 4 }}
    app: {{ include "simple-duty-web.fullname" . }}
    component: service-account
    {{- with .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}