{{- if and .Values.enabled .Values.cert.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apiserver.certSecretName" . }}
  namespace: {{ include "apiserver.namespace" . }}
  labels:
    {{- include "apiserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
    app.kubernetes.io/name: secret
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ ( include "apiserver.genCerts" . ) | indent 2 }}
{{- end }}

