{{- if and .Values.enabled .Values.webhook.enabled }}
{{- if and (eq (include "controller.certManagerEnabled" .) "true") (or (.Values.webhook.cert.issuer.create | default false) (.Values.webhook.cert.createIssuer | default false)) }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ if and .Values.webhook.cert.issuer .Values.webhook.cert.issuer.name }}{{ .Values.webhook.cert.issuer.name }}{{ else }}selfsigned-issuer{{ end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
spec:
  selfSigned: {}
{{- end }}
{{- end }}

