---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
  name: nvidia-tesla-v100-pcie-32gb
spec:
  alias:
  - V100
  - Volta V100
  - NVIDIA-Tesla V100-PCIE-32GB
  compute: "7.0"
  computeCapabilities:
  - precision: FP32
    unit: TFLOPS
    value: "19.5"
  - precision: FP16
    unit: TFLOPS
    value: "312"
  - precision: BF16
    unit: TFLOPS
    value: "312"
  - precision: FP8
    unit: TFLOPS
    value: "624"
  core: 100
  description: NVIDIA Tesla V100 PCIE 32GB GPU
  family: Volta
  manufacturer: NVIDIA
  memorySize: 32768
  memoryStep: 256
  model: NVIDIA-Tesla V100-PCIE-32GB
  supportComputeSplitMode:
  - hami-core
  supportVirtualDevice: true
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-v100-half-16gb
spec:
  core: 50
  manufacturer: NVIDIA
  memorySize: 16384
  model: NVIDIA-Tesla V100-PCIE-32GB
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-v100-quarter-8gb
spec:
  core: 25
  manufacturer: NVIDIA
  memorySize: 8192
  model: NVIDIA-Tesla V100-PCIE-32GB
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-v100-eighth-4gb
spec:
  core: 12
  manufacturer: NVIDIA
  memorySize: 4096
  model: NVIDIA-Tesla V100-PCIE-32GB

