apiVersion: device.theriseunion.io/v1alpha1
kind: GlobalConfig
metadata:
  name: global-config
spec:
  alertLevel:
  - critical
  - high
  gpuScheduling: spread
  nodeScheduling: binpack
  resourceAwareness: allocation_rate
  resourcePoolEnabled: false
  license: cO2syd/KBSfMYzLzJaVZISPFhCj/P5aym3hoXVnp6POkfzyqFp7JI7XZNRH9I/tyIIaQU+Msh4zSBnDof8E6QFJVizdgtDFqsW0JClBXzVr5iPBR2QTkXaRYqtt+ImLTHczWPF2tHex5ghf8QYRoRqLpTq3JaDgEA4dJt3LantcOz6+pOx6qaJ5AMI5jrOIkhzV5kL9mZOKTd3kgNipDiEYGte0ArQjqoBSscnHhVKO5AgsV60BWDmu2tKg3UwQPnwcLxMIHY6H4XsOvCQQ1FScQfM87e2lYDn01X2mtMC780Bh7zq8ahSQkP9jKEgbwB/CXF5O0YmMCkaVW3dKnva0XooVHVAVHc6YgMrzbPSxPzlvrN0XmLcl1k16CUwRV9QjrkRuz+sqaIxglDV+a7CBV0kVeyxbrtOLCoC/WVP+FC8FjHru5iYFcZMivCls7HEazbD2/f+LGtJPQPR4tgoAiRFsQLkAu/jhP78Y/cBxx7lRzzA18R81S76COy5WC
