---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
  name: nvidia-nvidia-a30
spec:
  alias:
  - A30
  - Ampere A30
  - NVIDIA-NVIDIA A30
  compute: "8.0"
  computeCapabilities:
  - precision: FP32
    unit: TFLOPS
    value: "10.3"
  - precision: FP16
    unit: TFLOPS
    value: "165"
  - precision: BF16
    unit: TFLOPS
    value: "165"
  core: 100
  description: NVIDIA A30 Tensor Core GPU with 24GB memory
  family: Ampere
  manufacturer: NVIDIA
  memorySize: 24576
  memoryStep: 256
  model: NVIDIA-NVIDIA A30
  supportComputeSplitMode:
  - mig
  - hami-core
  supportVirtualDevice: true
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-a30-half-12gb
spec:
  core: 50
  manufacturer: NVIDIA
  memorySize: 12288
  model: NVIDIA-NVIDIA A30
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-a30-quarter-6gb
spec:
  core: 25
  manufacturer: NVIDIA
  memorySize: 6144
  model: NVIDIA-NVIDIA A30
---
apiVersion: device.theriseunion.io/v1alpha1
kind: DeviceModel
metadata:
  labels:
    theriseunion.io/config-type: fixed
    theriseunion.io/virtual-model: "true"
  name: nvidia-a30-eighth-3gb
spec:
  core: 12
  manufacturer: NVIDIA
  memorySize: 3072
  model: NVIDIA-NVIDIA A30
