{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.serviceAccountName" . }}
  namespace: {{ include "controller.namespace" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
    app.kubernetes.io/name: apiserver-project
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
