apiVersion: v1
kind: Service
metadata:
  name: edge-museum
  namespace: edge-system
  labels:
    app: edge-museum
    component: chartmuseum
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: edge-museum
