apiVersion: installer.theriseunion.io/v1alpha1
kind: Component
metadata:
  name: edge-controller
spec:
  componentType: controller
  namespace: edge-system
  releaseName: controller
  chartPath: /Users/neov/src/github.com/edgekeel/apiserver/edge-installer/edge-controller
  values:
    replicaCount: 1
    fullnameOverride: "controller"
    image:
      repository: quanzhenglong.com/edge/controller
      pullPolicy: IfNotPresent
      tag: "main"
    serviceAccount:
      create: true
      automount: true
    service:
      type: ClusterIP
      port: 8080
      targetPort: 8080
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    edge:
      controller:
        logLevel: info
        metricsPort: 8080
        healthPort: 8081
      rbacController:
        enabled: true
        watchNamespace: ""
