{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "edge-console.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edge-console.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingressRoute.entryPoint }}
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: {{ .Values.ingressRoute.priority }}
      services:
        - name: {{ include "edge-console.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.service.port }}
    - match: Path(`/`)
      kind: Rule
      priority: {{ .Values.ingressRoute.priority }}
      services:
        - name: {{ include "edge-console.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.service.port }}
{{- end }}
