apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
data:
  controller.yaml: |
    iot:
      platformAdmin:
        components:
        {{- range .Values.platformAdmin.components }}
        - {{ . }}
        {{- end }}
        images:
        {{- range $key, $value := .Values.platformAdmin.images }}
        - {{ $key }}: {{ $value }}
        {{- end }}
    imageRegistry: {{ .Values.configmap.ImageRegistry }}