apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-controller.fullname" . }}
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "edge-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edge-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "edge-controller.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.controller.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.controller.securityContext.runAsUser }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.service.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.controller.healthPort }}
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: {{ .Values.controller.logLevel }}
            - name: METRICS_ADDR
              value: ":{{ .Values.controller.metricsPort }}"
            - name: HEALTH_ADDR
              value: ":{{ .Values.controller.healthPort }}"
            - name: HOME
              value: /tmp
            - name: HELM_CACHE_HOME
              value: /tmp/.helm/cache
            - name: HELM_CONFIG_HOME
              value: /tmp/.helm/config
            - name: HELM_DATA_HOME
              value: /tmp/.helm/data
            - name: CHART_REPO_URL
              value: {{ .Values.controller.chartRepository.url | default (print "http://" (include "edge-controller.fullname" .) "-chartmuseum." .Release.Namespace ".svc:8080") }}
            {{- if .Values.chartmuseum.enabled }}
            - name: CHARTMUSEUM_ENABLED
              value: "true"
            {{- end }}
            {{- if eq .Values.global.mode "member" }}
            - name: CLUSTER_ROLE
              value: member
            {{- else }}
            - name: CLUSTER_ROLE
              value: host
            {{- end }}
            - name: VCLUSTER_VALUES_PATH
              value: /charts/config/vcluster-values-local.yaml
          volumeMounts:
            - name: helm-cache
              mountPath: /tmp/.helm
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: helm-cache
          emptyDir: {}