{{- if .Values.chartmuseum.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-controller.fullname" . }}-chartmuseum
  labels:
    {{- include "edge-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: chartmuseum
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "edge-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chartmuseum
  template:
    metadata:
      labels:
        {{- include "edge-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chartmuseum
    spec:
      containers:
      - name: chartmuseum
        image: "{{ .Values.chartmuseum.image.repository }}:{{ .Values.chartmuseum.image.tag }}"
        imagePullPolicy: {{ .Values.chartmuseum.image.pullPolicy }}
        args:
        - --port=8080
        env:
        - name: STORAGE
          value: {{ .Values.chartmuseum.env.STORAGE }}
        - name: STORAGE_LOCAL_ROOTDIR
          value: {{ .Values.chartmuseum.env.STORAGE_LOCAL_ROOTDIR }}
        - name: DISABLE_API
          value: "{{ .Values.chartmuseum.env.DISABLE_API }}"
        - name: ALLOW_OVERWRITE
          value: "{{ .Values.chartmuseum.env.ALLOW_OVERWRITE }}"
        - name: CONTEXT_PATH
          value: {{ .Values.chartmuseum.env.CONTEXT_PATH }}
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.chartmuseum.resources | nindent 12 }}
{{- end }}