{{- if .Values.exporter.ascend.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hami-vgpu.exporter" . }}-ascend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ include "hami-vgpu.exporter" . }}-ascend
    {{- include "hami-vgpu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "hami-vgpu.exporter" . }}-ascend
      {{- include "hami-vgpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.exporter.ascend.containerPort | default 8082 | quote }}
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: {{ include "hami-vgpu.exporter" . }}-ascend
        {{- include "hami-vgpu.selectorLabels" . | nindent 8 }}
      name: ascend-exporter
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: ascend
                    operator: In
                    values:
                      - "on"
              - matchExpressions:
                  - key: volcano_ascend
                    operator: In
                    values:
                      - "on"
      {{- with .Values.exporter.ascend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ascend-exporter
        image: {{ .Values.exporter.ascend.image }}
        imagePullPolicy: {{ .Values.exporter.ascend.imagePullPolicy | default "IfNotPresent" }}
        command: [ "/bin/bash", "-c", "--"]
        args: [ "umask 027;npu-exporter -port=8082 -ip=0.0.0.0  -updateTime=5 -logFile=/var/log/mindx-dl/npu-exporter/npu-exporter.log -logLevel=0 -containerMode=docker" ]
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
          runAsGroup: 0
        {{- if .Values.exporter.ascend.resources }}
        resources:
          {{- toYaml .Values.exporter.ascend.resources | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.exporter.ascend.containerPort | default 8082 }}
            hostPort: {{ .Values.exporter.ascend.service.httpPort }}
            protocol: TCP
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: log-ascend-exporter
            mountPath: /var/log/mindx-dl/npu-exporter
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
            readOnly: true
          - name: ascend-dcmi
            mountPath: /usr/local/dcmi
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: docker-shim
            mountPath: /var/run/dockershim.sock
            readOnly: true
          - name: docker
            mountPath: /var/run/docker
            readOnly: true
          - name: cri-dockerd
            mountPath: /var/run/cri-dockerd.sock
            readOnly: true
          - name: containerd
            mountPath: /run/containerd
            readOnly: true
          - name: isulad
            mountPath: /run/isulad.sock
            readOnly: true
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: log-ascend-exporter
          hostPath:
            path: /var/log/mindx-dl/npu-exporter
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: ascend-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: ascend-dcmi
          hostPath:
            path: /usr/local/dcmi
        - name: sys
          hostPath:
            path: /sys
        - name: docker-shim
          hostPath:
            path: /var/run/dockershim.sock
        - name: docker
          hostPath:
            path: /var/run/docker
        - name: cri-dockerd
          hostPath:
            path: /var/run/cri-dockerd.sock
        - name: containerd
          hostPath:
            path: /run/containerd
        - name: isulad
          hostPath:
            path: /run/isulad.sock
        - name: tmp
          hostPath:
            path: /tmp
{{- end }}
