{{- if .Values.edge.auth.oauth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-apiserver.fullname" . }}-oauth-clients
  labels:
    {{- include "edge-apiserver.labels" . | nindent 4 }}
data:
  clients.yaml: |
    clients:
      {{- range .Values.edge.auth.oauth.clients }}
      {{ .clientId }}: {{ .clientSecret | quote }}
      {{- end }}
{{- end }}