{{- if .Values.exporter.cambricon.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.exporter" . }}-mlu
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: hami-exporter-mlu
    {{- include "hami-vgpu.labels" . | nindent 4 }}
{{- end }}