{{- if .Values.devices.kunlunxin.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}-xpu
subjects:
  - kind: ServiceAccount
    name: {{ include "hami-vgpu.device-plugin" . }}-xpu
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "hami-vgpu.device-plugin" . }}-xpu
  apiGroup: rbac.authorization.k8s.io
{{- end }}