{{- if .Values.devices.kunlunxin.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}-xpu
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: hami-device-plugin-xpu
    {{- include "hami-vgpu.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations }}
  annotations: {{ toYaml .Values.global.annotations | nindent 4}}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hami-device-plugin-xpu
      {{- include "hami-vgpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hami-device-plugin-xpu
        hami.io/webhook: ignore
        {{- include "hami-vgpu.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: "system-node-critical"
      serviceAccountName: {{ include "hami-vgpu.device-plugin" . }}-xpu
      containers:
        - image: {{ .Values.devices.kunlunxin.image }}
          imagePullPolicy: {{ .Values.devices.kunlunxin.imagePullPolicy | quote }}
          name: device-plugin
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 500m
          args:
            - xpu-device-plugin
            - --memory-unit=MiB
            - -logtostderr
            {{- range .Values.devices.kunlunxin.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add: [ "ALL" ]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: xre
              mountPath: /usr/local/xpu
            - name: dev
              mountPath: /dev
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBECONFIG
              value: /etc/kubernetes/kubelet.conf
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: xre
          hostPath:
            path: /usr/local/xpu
        - name: dev
          hostPath:
            path: /dev
      {{- if .Values.devices.kunlunxin.nodeSelector }}
      nodeSelector: {{ toYaml .Values.devices.kunlunxin.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.devices.kunlunxin.tolerations }}
      tolerations: {{ toYaml .Values.devices.kunlunxin.tolerations | nindent 8 }}
      {{- end }}
{{- end }}