{{- if .Values.duty.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "duty.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "duty.labels" . | nindent 4 }}
    app: {{ include "duty.backend.fullname" . }}
    component: service-account
  {{- with .Values.duty.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}