apiVersion: v1
kind: Service
metadata:
  name: {{ include "duty.backend.fullname" . }}
  labels:
    {{- include "duty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.duty.service.type }}
  ports:
    - port: {{ .Values.duty.service.port }}
      targetPort: {{ .Values.duty.service.httpPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.duty.service.type "NodePort") .Values.duty.service.nodePort }}
      nodePort: {{ .Values.duty.service.nodePort }}
      {{- end }}
  selector:
    {{- include "duty.selectorLabels" . | nindent 4 }}
