{{- if .Values.devices.enflameshare.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}-gcushare
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "update", "watch", "patch"]
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "configmaps"]
    verbs: ["get", "patch", "update", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["patch", "update"]
{{- end }}