{{- if .Values.devices.enflameshare.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}-gcushare  
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hami-vgpu.device-plugin" . }}-gcushare
subjects:
- kind: ServiceAccount
  name: {{ include "hami-vgpu.device-plugin" . }}-gcushare
  namespace: {{ .Release.Namespace | quote }}
{{- end }}