apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcore
  namespace: {{ include "kubeedge.namespace" . }}
  labels:
    {{- include "kubeedge.cloudcore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cloudCore.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeedge.cloudcore.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeedge.cloudcore.labels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.cloudCore.hostNetwork }}
      {{- if .Values.cloudCore.hostNetwork }}
      dnsPolicy: {{ .Values.cloudCore.dnsPolicy }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.cloudCore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "kubeedge.serviceAccountName" . }}
      {{- include "kubeedge.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: cloudcore
        image: {{ include "kubeedge.cloudCoreImage" . }}
        imagePullPolicy: {{ .Values.cloudCore.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.cloudHub.websocket.port }}
          name: cloudhub
          protocol: TCP
        - containerPort: {{ .Values.cloudHub.quic.port }}
          name: cloudhub-quic
          protocol: TCP
        - containerPort: {{ .Values.cloudHub.https.port }}
          name: cloudhub-https
          protocol: TCP
        - containerPort: {{ .Values.cloudStream.streamPort }}
          name: cloudstream
          protocol: TCP
        - containerPort: {{ .Values.cloudStream.tunnelPort }}
          name: tunnelport
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /etc/kubeedge/config
        - name: certs
          mountPath: /etc/kubeedge
        - name: sock
          mountPath: /var/lib/kubeedge
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
        {{- with .Values.cloudCore.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cloudCore.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: conf
        configMap:
          name: cloudcore
      - name: certs
        secret:
          secretName: cloudcore
          items:
          - key: stream.crt
            path: certs/stream.crt
          - key: stream.key
            path: certs/stream.key
          - key: streamCA.crt
            path: ca/streamCA.crt
      - name: sock
        hostPath:
          path: /var/lib/kubeedge
          type: DirectoryOrCreate
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      {{- with .Values.cloudCore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cloudCore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
