apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-pools-cm
  {{- if has "resourcePoolCM" .Values.nonOverwrite }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install
  {{- end }}
data:
  resource_pools: |