apiVersion: v2
name: chartmuseum
description: ChartMuseum - Helm Chart Repository for Edge Platform
type: application
version: 0.1.0
appVersion: "main-qzl"
home: https://github.com/helm/chartmuseum
maintainers:
  - name: Edge Team
    email: dev@edge.io
keywords:
  - chartmuseum
  - helm
  - repository
  - chart
sources:
  - https://github.com/helm/chartmuseum
