apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-ota.fullname" . }}
  namespace: {{ include "edge-ota.namespace" . }}
  labels:
    {{- include "edge-ota.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "edge-ota.selectorLabels" . | nindent 4 }}
