apiVersion: v1
data:
  controller.yaml: {{ .Values.configMap.controller | nindent 2 }}
kind: ConfigMap
metadata:
  name: {{ include "iot-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
