apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iot-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  controller.yaml: |{{ .Values.configMap.controller | nindent 4 }}